# Header

menu:
  首页: /
  产品: /tags/产品

# SubNav
subnav:
  github: 'http://github.com/yfsoftcom'
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  mail: 'mailto:yfsoftcom@126.com'
  #facebook: "#"
  #google: "#"
  twitter: 'http://twitter.com/yfsoftcom'
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
growingio_analytics: '984266f00491a1b4'
favicon: /favicon.png

#你的头像url
avatar: http://yfdocument.qiniudn.com/logo.png

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: true

#
smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  friends: '友情链接'
  aboutme: '关于我们'

#
friends:
  cnode: http://cnodejs.org/
  Blog: http://blog.yfsoft.biz/

#
aboutme: 专注改变
